SRC_DIR=$(BENCH_DIR)/src
SRC_OBJS=$(SRC_DIR)/sparselu.c $(SRC_DIR)/sparselu-seq.c $(SRC_DIR)/sparselu-task.c $(SRC_DIR)/sparselu-task-dep.c $(SRC_DIR)/main.c -lrt -lm -std=c99
INPUT_FLAGS=-t 2 -n 32 -m 32
INPUT_FLAGS_SEQUENTIAL=-s -n 32 -m 32
TIME_LIMIT=30
