SRC_DIR=$(BENCH_DIR)/src
SRC_OBJS=$(SRC_DIR)/jacobi-block-for.c $(SRC_DIR)/jacobi-block-task.c $(SRC_DIR)/jacobi-block-task-dep.c $(SRC_DIR)/jacobi-seq.c $(SRC_DIR)/jacobi-task.c $(SRC_DIR)/jacobi-task-dep.c $(SRC_DIR)/main.c $(SRC_DIR)/poisson.c -lrt -lm -std=c99
INPUT_FLAGS=-t 2
#INPUT_FLAGS=-t 2 -n 64 -b 1
INPUT_FLAGS_SEQUENTIAL=-s
#INPUT_FLAGS_SEQUENTIAL=-s -n 64 -b 1
TIME_LIMIT=20
